// Test-only TLS material for the namespace remote-attestation suite.
//
// SECURITY CONTRACT
// ----------------
// Nothing generated by this module is committed to the repository or written
// to disk. The certificate and private key are created from scratch inside the
// running test process and retained only by that process-level fixture cache.
// This key exists only during test execution and is never registered with any
// trust store or operational CA, never pinned by a deployment manifest, and
// never used against anything other than a loopback test listener. Treat any
// persisted copy of this material as garbage to be deleted, not as a credential.
//
// WHY GENERATION INSTEAD OF CHECKED-IN FIXTURES
// --------------------------------------------
// The previous localhost-test.p12 serialized a private key in Git, while the
// separate localhost-test.crt was the trust anchor used by the test client.
// Generating both halves in memory makes the repository's no-private-key
// contract true without weakening TLS verification or changing that trust
// relationship.
//
// CERTIFICATE PROFILE (identical in shape to the fixtures it replaces)
// -------------------------------------------------------------------
//   localhost    C=KR, O=MOLIT Namespace Test, OU=Test Fixture,
//                CN=localhost
//                RSA 2048, self-signed with SHA-256, SAN DNS:localhost
//                + IP:127.0.0.1, non-critical subjectKeyIdentifier,
//                no EKU, keyUsage, basicConstraints, or authorityKeyIdentifier
//
// VALIDITY AND GENERATION COST
// ----------------------------
// notBefore is backdated one hour from generation and notAfter is exactly 3650
// days later, matching the old certificate's validity span while avoiding a
// fixed certificate that eventually expires. Structure and profile are fixed;
// key and serial entropy intentionally come from Node's cryptographic RNG.
// Generation is synchronous, offline, cached once per test process, and takes
// tens of milliseconds on the supported Node runtime.
//
// WHY THE TEST NO LONGER USES PKCS#12
// -----------------------------------
// Node's standard modules can consume PKCS#12 but expose no PKCS#12 writer.
// The HTTPS API also accepts the same certificate and private key directly as
// cert and key, so doing that preserves the tested trust relationship without
// adding an openssl executable or third-party package dependency.

import { X509Certificate, createHash, generateKeyPairSync, randomBytes, sign } from "node:crypto";

const ONE_HOUR_MS = 60 * 60 * 1_000;
const TEN_YEARS_MS = 10 * 365 * 24 * 60 * 60 * 1_000;

function encodeLength(length) {
  if (length < 0x80) return Buffer.from([length]);
  const bytes = [];
  for (let value = length; value > 0; value = Math.floor(value / 256)) bytes.unshift(value % 256);
  return Buffer.from([0x80 | bytes.length, ...bytes]);
}

function tlv(tag, value) {
  return Buffer.concat([Buffer.from([tag]), encodeLength(value.length), value]);
}

const der = {
  sequence: (...parts) => tlv(0x30, Buffer.concat(parts)),
  set: (...parts) => tlv(0x31, Buffer.concat(parts)),
  integer: (value) => tlv(0x02, value),
  null: () => tlv(0x05, Buffer.alloc(0)),
  bitString: (value, unusedBits = 0) => tlv(0x03, Buffer.concat([Buffer.from([unusedBits]), value])),
  octetString: (value) => tlv(0x04, value),
  printableString: (value) => tlv(0x13, Buffer.from(value, "ascii")),
  contextPrimitive: (number, value) => tlv(0x80 | number, value),
  contextConstructed: (number, ...parts) => tlv(0xa0 | number, Buffer.concat(parts)),
  objectIdentifier(dotted) {
    const arcs = dotted.split(".").map(Number);
    const bytes = [40 * arcs[0] + arcs[1]];
    for (const arc of arcs.slice(2)) {
      const stack = [arc & 0x7f];
      for (let value = Math.floor(arc / 128); value > 0; value = Math.floor(value / 128)) stack.unshift((value & 0x7f) | 0x80);
      bytes.push(...stack);
    }
    return tlv(0x06, Buffer.from(bytes));
  },
};

function encodeTime(date) {
  const iso = date.toISOString();
  const tail = iso.slice(5, 7) + iso.slice(8, 10) + iso.slice(11, 13) + iso.slice(14, 16) + iso.slice(17, 19) + "Z";
  return date.getUTCFullYear() < 2050
    ? tlv(0x17, Buffer.from(iso.slice(2, 4) + tail, "ascii"))
    : tlv(0x18, Buffer.from(iso.slice(0, 4) + tail, "ascii"));
}

function serialNumber() {
  const bytes = randomBytes(8);
  bytes[0] &= 0x7f;
  if (bytes[0] === 0) bytes[0] = 1;
  return der.integer(bytes);
}

function distinguishedName() {
  return der.sequence(
    der.set(der.sequence(der.objectIdentifier("2.5.4.6"), der.printableString("KR"))),
    der.set(der.sequence(der.objectIdentifier("2.5.4.10"), der.printableString("MOLIT Namespace Test"))),
    der.set(der.sequence(der.objectIdentifier("2.5.4.11"), der.printableString("Test Fixture"))),
    der.set(der.sequence(der.objectIdentifier("2.5.4.3"), der.printableString("localhost"))),
  );
}

function extension(oid, value) {
  return der.sequence(der.objectIdentifier(oid), der.octetString(value));
}

function localhostSubjectAltNameExtension() {
  return extension("2.5.29.17", der.sequence(
    der.contextPrimitive(2, Buffer.from("localhost", "ascii")),
    der.contextPrimitive(7, Buffer.from([127, 0, 0, 1])),
  ));
}

function subjectKeyIdentifierExtension(publicKey) {
  const rsaPublicKey = publicKey.export({ format: "der", type: "pkcs1" });
  const identifier = createHash("sha1").update(rsaPublicKey).digest();
  return extension("2.5.29.14", der.octetString(identifier));
}

function toPem(label, body) {
  const base64 = body.toString("base64").replace(/(.{64})/gu, "$1\n").replace(/\n$/u, "");
  return "-----BEGIN " + label + "-----\n" + base64 + "\n-----END " + label + "-----\n";
}

const SHA256_WITH_RSA = der.sequence(
  der.objectIdentifier("1.2.840.113549.1.1.11"),
  der.null(),
);

function issueSelfSignedCertificate({ keyPair, notBefore, notAfter }) {
  const name = distinguishedName();
  const extensions = [
    subjectKeyIdentifierExtension(keyPair.publicKey),
    localhostSubjectAltNameExtension(),
  ];
  const tbsCertificate = der.sequence(
    der.contextConstructed(0, der.integer(Buffer.from([2]))),
    serialNumber(),
    SHA256_WITH_RSA,
    name,
    der.sequence(encodeTime(notBefore), encodeTime(notAfter)),
    name,
    keyPair.publicKey.export({ format: "der", type: "spki" }),
    der.contextConstructed(3, der.sequence(...extensions)),
  );
  const signature = sign("sha256", tbsCertificate, keyPair.privateKey);
  return toPem("CERTIFICATE", der.sequence(
    tbsCertificate,
    SHA256_WITH_RSA,
    der.bitString(signature),
  ));
}

function assertCertificateProfile(certificate, { notBefore, notAfter }) {
  const expectedName = "C=KR\nO=MOLIT Namespace Test\nOU=Test Fixture\nCN=localhost";
  const details = certificate.publicKey.asymmetricKeyDetails;
  if (certificate.subject !== expectedName || certificate.issuer !== expectedName) {
    throw new Error("generated namespace certificate has the wrong distinguished name");
  }
  if (!certificate.checkIssued(certificate) || !certificate.verify(certificate.publicKey)) {
    throw new Error("generated namespace certificate is not self-signed");
  }
  if (certificate.checkHost("localhost") !== "localhost" || certificate.checkIP("127.0.0.1") !== "127.0.0.1") {
    throw new Error("generated namespace certificate has the wrong subject alternative names");
  }
  if (certificate.keyUsage !== undefined || certificate.ca) {
    throw new Error("generated namespace certificate gained an EKU or CA constraint");
  }
  if (certificate.publicKey.asymmetricKeyType !== "rsa" || details?.modulusLength !== 2048 || details?.publicExponent !== 65537n) {
    throw new Error("generated namespace certificate has the wrong RSA profile");
  }
  if (certificate.validFromDate.getTime() !== notBefore.getTime() || certificate.validToDate.getTime() !== notAfter.getTime()) {
    throw new Error("generated namespace certificate has the wrong validity window");
  }
}

/** Build one self-consistent, in-memory namespace TLS identity. */
export function generateNamespaceTlsMaterial({ now = new Date(), backdateMs = ONE_HOUR_MS, lifetimeMs = TEN_YEARS_MS } = {}) {
  const notBefore = new Date(Math.floor((now.getTime() - backdateMs) / 1_000) * 1_000);
  const notAfter = new Date(notBefore.getTime() + lifetimeMs);
  const { privateKey, publicKey } = generateKeyPairSync("rsa", { modulusLength: 2048, publicExponent: 0x10001 });
  const certificatePem = issueSelfSignedCertificate({ keyPair: { privateKey, publicKey }, notBefore, notAfter });
  const privateKeyPem = privateKey.export({ format: "pem", type: "pkcs8" });
  const certificate = new X509Certificate(certificatePem);
  assertCertificateProfile(certificate, { notBefore, notAfter });

  return Object.freeze({
    certificate: certificatePem,
    privateKey: privateKeyPem,
    notBefore,
    notAfter,
  });
}

let cached = null;

/** Generate once per test process and reuse for every test in the suite. */
export function namespaceTlsFixtures() {
  cached ??= generateNamespaceTlsMaterial();
  return cached;
}
