/*
 * Derived for local/CI testing from the Eclipse EDC Samples vault seed pattern.
 * SPDX-License-Identifier: Apache-2.0
 */
package org.eclipse.edc.molit.smoke;

import org.eclipse.edc.runtime.metamodel.annotation.Setting;
import org.eclipse.edc.spi.EdcException;
import org.eclipse.edc.spi.security.Vault;
import org.eclipse.edc.spi.system.ServiceExtension;
import org.eclipse.edc.spi.system.ServiceExtensionContext;
import org.eclipse.edc.runtime.metamodel.annotation.Inject;

import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyStore;
import java.security.PrivateKey;
import java.util.Base64;

/**
 * Loads an ephemeral PKCS#12 key generated by the smoke-compose keygen service.
 * This extension is not present in the production data-plane artifact.
 */
public class EphemeralKeyStoreExtension implements ServiceExtension {

    @Setting(key = "edc.molit.smoke.enabled", description = "Explicit opt-in for the local/CI smoke extensions", defaultValue = "false")
    private boolean enabled;

    @Setting(key = "edc.molit.smoke.keystore.path", description = "Path to an ephemeral PKCS#12 keystore", required = false)
    private String keyStorePath;

    @Setting(key = "edc.molit.smoke.keystore.password.path", description = "Path to the ephemeral keystore password", required = false)
    private String passwordPath;

    @Setting(key = "edc.molit.smoke.keystore.alias", description = "Key alias", defaultValue = "smoke-key")
    private String alias;

    @Setting(key = "edc.transfer.proxy.token.signer.privatekey.alias", description = "Vault alias used by EDC to sign an EDR token")
    private String vaultAlias;

    @Inject
    private Vault vault;

    @Override
    public void initialize(ServiceExtensionContext context) {
        requireSmokeOptIn();
        try {
            var password = Files.readString(Path.of(passwordPath)).trim().toCharArray();
            var keyStore = KeyStore.getInstance("PKCS12");
            try (InputStream input = Files.newInputStream(Path.of(keyStorePath))) {
                keyStore.load(input, password);
            }
            var key = keyStore.getKey(alias, password);
            if (!(key instanceof PrivateKey privateKey)) {
                throw new EdcException("Smoke keystore alias does not contain a private key: " + alias);
            }
            var pem = "-----BEGIN PRIVATE KEY-----\n"
                    + Base64.getMimeEncoder(64, new byte[]{'\n'}).encodeToString(privateKey.getEncoded())
                    + "\n-----END PRIVATE KEY-----\n";
            vault.storeSecret(vaultAlias, pem);
        } catch (Exception e) {
            throw e instanceof EdcException edcException
                    ? edcException
                    : new EdcException("Cannot load the ephemeral smoke key: " + e.getMessage(), e);
        }
    }

    private void requireSmokeOptIn() {
        if (!enabled) {
            throw new EdcException("Smoke-only EDC artifact requires edc.molit.smoke.enabled=true");
        }
        if (keyStorePath == null || passwordPath == null) {
            throw new EdcException("Smoke keystore and password paths are required");
        }
    }
}
