edc.participant.id=consumer
edc.component.id=consumer-data-plane

web.http.port=8080
web.http.path=/api
web.http.control.port=8083
web.http.control.path=/control
edc.control.endpoint=http://consumer-data-plane:8083/control
edc.dpf.selector.url=http://consumer-control-plane:8083/control/v1/dataplanes

edc.transfer.proxy.token.signer.privatekey.alias=private-key
edc.transfer.proxy.token.verifier.publickey.alias=public-key
edc.dataplane.http.sink.partition.size=1
edc.dataplane.send.retry.limit=3
edc.dataplane.state-machine.iteration-wait-millis=100

edc.datasource.default.url=jdbc:postgresql://postgres:5432/consumer_dp
edc.datasource.default.user=edc
edc.datasource.default.driverClassName=org.postgresql.Driver
edc.sql.schema.autocreate=true
